diff --git a//dev/null b/data.js
index 0000000000000000000000000000000000000000..e80ac04474d270a45916d730ed9db2d2e0248227 100644
--- a//dev/null
+++ b/data.js
@@ -0,0 +1,297 @@
+const fishData = [
+  {
+    id: "ammonite",
+    name: "Ammonite",
+    rarity: "Legendary",
+    type: "Sea Creature",
+    basePrice: 245000,
+    notes: "Scales with Heart of the Mountain level.",
+    preferredLocations: ["Crimson Isle", "Deep Caverns"],
+  },
+  {
+    id: "prismarine",
+    name: "Prismarine Fish",
+    rarity: "Rare",
+    type: "Standard",
+    basePrice: 2100,
+    notes: "Consistent demand for Prismarine Weaponsmith.",
+    preferredLocations: ["The Park", "Jerry Pond"],
+  },
+  {
+    id: "frozen",
+    name: "Frozen Treasure",
+    rarity: "Epic",
+    type: "Treasure",
+    basePrice: 88000,
+    notes: "Sought after during Marina's fishing festivals.",
+    preferredLocations: ["Jerry Pond"],
+  },
+  {
+    id: "worm",
+    name: "Worm",
+    rarity: "Uncommon",
+    type: "Sea Creature",
+    basePrice: 1750,
+    notes: "Essential bait crafting material in the Dwarven Mines.",
+    preferredLocations: ["Crystal Hollows", "Dwarven Mines"],
+  },
+  {
+    id: "golden-fish",
+    name: "Golden Fish",
+    rarity: "Mythic",
+    type: "Event",
+    basePrice: 420000,
+    notes: "Rare catch during Fishing Festival with high demand for museum drops.",
+    preferredLocations: ["Hub", "Crystal Hollows"],
+  },
+  {
+    id: "sulphur",
+    name: "Sulphur Skitter",
+    rarity: "Legendary",
+    type: "Sea Creature",
+    basePrice: 162000,
+    notes: "Best targeted with Thunder in Crimson Isle.",
+    preferredLocations: ["Crimson Isle"],
+  },
+  {
+    id: "shredder",
+    name: "Great White Shark Tooth",
+    rarity: "Legendary",
+    type: "Shark",
+    basePrice: 630000,
+    notes: "Used for Shark Armor upgrades.",
+    preferredLocations: ["Fishing Festival"],
+  },
+  {
+    id: "spider",
+    name: "Spider Fish",
+    rarity: "Uncommon",
+    type: "Standard",
+    basePrice: 1100,
+    notes: "Abundant at the Spider's Den pond.",
+    preferredLocations: ["Spider's Den"],
+  },
+  {
+    id: "night-squid",
+    name: "Night Squid",
+    rarity: "Rare",
+    type: "Sea Creature",
+    basePrice: 3150,
+    notes: "Catch rate jumps dramatically during rain.",
+    preferredLocations: ["The Park", "Hub"],
+  },
+  {
+    id: "sea-walker",
+    name: "Sea Walker",
+    rarity: "Common",
+    type: "Sea Creature",
+    basePrice: 780,
+    notes: "Great for early-game fishing collections.",
+    preferredLocations: ["Hub", "Spider's Den"],
+  },
+  {
+    id: "carrot-king",
+    name: "Carrot King",
+    rarity: "Legendary",
+    type: "Sea Creature",
+    basePrice: 505000,
+    notes: "Requires Carrot Bait; high value for pet crafting.",
+    preferredLocations: ["The Park"],
+  },
+  {
+    id: "yeti",
+    name: "Yeti",
+    rarity: "Legendary",
+    type: "Winter",
+    basePrice: 925000,
+    notes: "Drops Yeti Pet and Enchanted Packed Ice.",
+    preferredLocations: ["Jerry Pond"],
+  },
+];
+
+const locationData = [
+  {
+    id: "hub",
+    name: "Hub - Mountain Pond",
+    baseCatchesPerHour: 95,
+    treasureChance: 0.06,
+    seaCreatureChance: 0.32,
+    description: "Balanced fishing with easy access and Marina boosts.",
+    fishDistribution: {
+      "sea-walker": 0.22,
+      "night-squid": 0.15,
+      prismarine: 0.2,
+      worm: 0.1,
+      "golden-fish": 0.01,
+      default: 0.32,
+    },
+  },
+  {
+    id: "crimson",
+    name: "Crimson Isle Lava Pools",
+    baseCatchesPerHour: 78,
+    treasureChance: 0.08,
+    seaCreatureChance: 0.4,
+    description: "High-risk, high-reward lava fishing with Sulphur creatures.",
+    fishDistribution: {
+      sulphur: 0.18,
+      ammonite: 0.12,
+      worm: 0.15,
+      "golden-fish": 0.015,
+      default: 0.535,
+    },
+  },
+  {
+    id: "park",
+    name: "The Park - Rainy Pond",
+    baseCatchesPerHour: 105,
+    treasureChance: 0.05,
+    seaCreatureChance: 0.38,
+    description: "Rain boosts squid and Carrot King chance.",
+    fishDistribution: {
+      prismarine: 0.22,
+      "night-squid": 0.18,
+      "carrot-king": 0.04,
+      worm: 0.12,
+      default: 0.44,
+    },
+  },
+  {
+    id: "jerry",
+    name: "Jerry Pond",
+    baseCatchesPerHour: 88,
+    treasureChance: 0.12,
+    seaCreatureChance: 0.41,
+    description: "Winter wonderland with Yetis and Frozen Treasures.",
+    fishDistribution: {
+      frozen: 0.08,
+      yeti: 0.05,
+      prismarine: 0.16,
+      worm: 0.1,
+      default: 0.61,
+    },
+  },
+  {
+    id: "spider-den",
+    name: "Spider's Den Pond",
+    baseCatchesPerHour: 112,
+    treasureChance: 0.03,
+    seaCreatureChance: 0.28,
+    description: "Fast catch rate with common mobs and Spider Fish.",
+    fishDistribution: {
+      spider: 0.32,
+      prismarine: 0.2,
+      "sea-walker": 0.2,
+      worm: 0.08,
+      default: 0.2,
+    },
+  },
+];
+
+const gearData = {
+  rods: [
+    {
+      id: "augur",
+      name: "Auger Rod",
+      catchMultiplier: 1.22,
+      priceMultiplier: 1,
+      festivalBoost: 1.05,
+      notes: "Excels in cold biomes; strong for Yeti and Frozen Treasure.",
+    },
+    {
+      id: "inferno",
+      name: "Inferno Rod",
+      catchMultiplier: 1.18,
+      priceMultiplier: 1.1,
+      festivalBoost: 1.02,
+      notes: "Specialized for Crimson Isle lava fishing.",
+    },
+    {
+      id: "shredder",
+      name: "Shredder",
+      catchMultiplier: 1.15,
+      priceMultiplier: 1.06,
+      festivalBoost: 1.03,
+      notes: "All-rounder rod with shark tooth synergy.",
+    },
+    {
+      id: "challenger",
+      name: "Challenger Rod",
+      catchMultiplier: 1.08,
+      priceMultiplier: 1,
+      festivalBoost: 1.08,
+      notes: "Budget option that shines during festivals.",
+    },
+  ],
+  armor: [
+    {
+      id: "shark",
+      name: "Great White Shark Armor",
+      catchMultiplier: 1.16,
+      priceMultiplier: 1.08,
+      notes: "Boosts shark loot profits and sea creature chance.",
+    },
+    {
+      id: "aurora",
+      name: "Aurora Armor",
+      catchMultiplier: 1.1,
+      priceMultiplier: 1.12,
+      notes: "Magic find synergy increases valuable drop prices.",
+    },
+    {
+      id: "angler",
+      name: "Angler Armor",
+      catchMultiplier: 1.04,
+      priceMultiplier: 1,
+      notes: "Easy early-game set perfect for Spider's Den.",
+    },
+    {
+      id: "diver",
+      name: "Diver's Armor",
+      catchMultiplier: 1.12,
+      priceMultiplier: 1.05,
+      notes: "Balanced stats for all-purpose fishing.",
+    },
+  ],
+  pets: [
+    {
+      id: "dolphin",
+      name: "Legendary Dolphin",
+      catchMultiplier: 1.18,
+      priceMultiplier: 1.04,
+      notes: "Party fishing synergy and high catch speed.",
+    },
+    {
+      id: "squid",
+      name: "Flying Fish",
+      catchMultiplier: 1.12,
+      priceMultiplier: 1.1,
+      notes: "Boosts fishing speed and pet luck for valuable drops.",
+    },
+    {
+      id: "ammonite",
+      name: "Ammonite Pet",
+      catchMultiplier: 1.07,
+      priceMultiplier: 1.08,
+      notes: "Mining stat scaling great for Crystal Hollows.",
+    },
+    {
+      id: "blue-whale",
+      name: "Blue Whale",
+      catchMultiplier: 1.05,
+      priceMultiplier: 1,
+      notes: "Defensive option for lava fishing.",
+    },
+  ],
+};
+
+const buffs = {
+  festival: {
+    catchMultiplier: 1.12,
+    priceMultiplier: 1.04,
+  },
+  doubleHook: {
+    catchMultiplier: 1.25,
+    priceMultiplier: 1,
+  },
+};
